# Generated by Django 3.2.5 on 2021-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('stable', 'stable'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='cancelled', max_length=10, verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
