# Generated by Django 3.2.5 on 2021-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReportModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('first_date', models.DateTimeField()),
                ('second_date', models.DateTimeField()),
                ('summary_report', models.TextField(blank=True, null=True, verbose_name='Отчет')),
            ],
        ),
    ]
