# Generated by Django 3.2.5 on 2021-07-21 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_summaryreportmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryreportmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='summaryreportmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summaryreportmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Имя Отчета'),
        ),
        migrations.AddField(
            model_name='summaryreportmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='summaryreportmodel',
            name='summary_report',
            field=models.FileField(default=django.utils.timezone.now, upload_to='SummaryReports', verbose_name='CSV файл отчета'),
            preserve_default=False,
        ),
    ]
